### ISSUE TITLE
More Usage Examples

### ISSUE THREAD

**Issue by Gnyasha** [ChustaSoft/StaticData#35]
If possible kindly assist in adding some usage examples. Like a .net core console project usage. Library seems great.

**Comment by xaberue** [comment]
Hi @Gnyasha !!!

First of all thanks for having a look on our tool.

Unfortunately, the library is currently stable but inactive, so it is not expected to launch new versions or examples for it...

However, you can take a look at the example codes of the [IntegrationTests](https://github.com/ChustaSoft/StaticData/tree/master/ChustaSoft.Services.StaticData.IntegrationTest/TestServices), where you can find calls examples for almost all supported scenarios. If you need a specific example that you cannot find, or that you need help, we can also help you, but we would need a specific example on which you need it.

Additionally, the library is 100% open to suggestions for improvement and contributions. :)

I hope the information can be of help to you.

Best regards

**Comment by Gnyasha** [comment]
Thanks much, I will check the link you provided.
