### ISSUE TITLE
Area field in Country model needs to be double, not int

### ISSUE THREAD

**Issue by epamELitosh** [ChustaSoft/StaticData#36]
Hello,
There is a major issue with Area field in Country.cs model. It's int while some counties have non-integer area value. For example Gibraltar(6.5), Vatican(0.44)... So the JsonConverter could not deserialize this countries.

**Comment by xaberue** [comment]
Hi @epamELitosh 

Thanks for reporting,

Taking in advantage the required basic maintenance for this tool, we will publish a new version with support to latest .NET versions and fixing this issue.

Many thanks

**Comment by xaberue** [comment]
Version [2.2.0] published
